modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/PackMode/issues"
license="MIT"

[[mods]]
    modId="packmode"
    version="${file.jarVersion}"
    displayName="Pack Mode"
    authors="SkySom"
    description='''
        Allows Pack Makers to provide different combinations of pack modes
    '''

[[dependencies.packmode]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"